select
    team_season_id,
    season,
    team_id,
    team_name,
    conference_name,
    -- Identity rather than measurement. Both are nullable: the synthetic demo
    -- seasons carry neither, and every page that draws a logo falls back to
    -- the team's initials rather than a broken image.
    team_logo_url,
    team_color,
    record,
    conference_record,
    wins,
    losses,
    win_pct,
    avg_margin,
    games_played,
    adjusted_offensive_efficiency,
    adjusted_defensive_efficiency,
    adjusted_efficiency_margin,
    adjusted_tempo,
    elo_rating,
    srs_rating,
    strength_of_schedule,
    wins_vs_top_50,
    games_vs_top_50,
    last_10_wins,
    last_10_games,
    effective_fg_pct,
    effective_fg_pct_allowed,
    turnover_pct,
    turnover_pct_forced,
    offensive_rebound_pct,
    defensive_rebound_pct,
    free_throw_rate,
    three_point_pct,
    national_rank,
    conference_rank,
    offense_rank,
    defense_rank,
    tempo_rank,
    schedule_strength_rank,
    made_ncaa_tournament,
    ncaa_tournament_wins,
    won_national_championship
from marts.mart_team_season
